### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by MissAllSunday** [MissAllSunday/zim#3]
#### A reminder of stuff  I want to implement

- [x] Add htmlawed or htmlpurifier as services
- [ ] use the "afterroute" method to set the needed meta tags and all that other stuff? 
- [x] Modify the editor to auto insert the structured data crap to every posted image
- [ ] Build a doge gif  utterly important!
- [ ] Automatize the metatags creation
- [x] Build filters based on tags
- [ ] ????
- [ ] PROFIT!!1!!eleventeen!!

**Comment by MissAllSunday** [comment]
I got an idea for using the afterroute event, unfortunately I forgot about it...

Automatize the metatag creating isn't possible, best I can do is set a generic array and overwrite those default values which is what I'm currently using.
